[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.26"
via_ir = false
remappings = [
    "@uniswap/v4-core/=lib/v4-core/",
    "@uniswap/v4-periphery/=lib/v4-periphery/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "forge-std/=lib/forge-std/src/"
]

[rpc_endpoints]
base = "https://mainnet.base.org"

[profile.fork]
eth_rpc_url = "https://mainnet.base.org"
